language: python
python: 2.7
install: "pip install Lektor"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
script: "cd zoidbergwill.github.io/ && lektor build && lektor deploy ghpages"
