title: Fantastic Bugs and How to Replicate Them
email: zoidbergwill@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zoidbergwill.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zoidbergwill
github_username:  zoidbergwill

# Build settings
markdown: kramdown
theme: minima
google_analytics: 'UA-130590976-1'
font-awesome:
  assets: true
plugins:
  - jemoji
  - jekyll-font-awesome-sass
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
